settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: fcode.biz
    name: fcode.biz
    description: 'Fshare code'
    url: 'https://fcode.biz'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: fcode.vn
    name: fcode.vn
    description: 'Fcode Shop'
    url: 'https://fcode.vn'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
